// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package gRPC.com.protos;

public interface DataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes data = 1;</code>
   */
  com.google.protobuf.ByteString getData();
}
