// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package gRPC.com.protos;

public interface DataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>bytes data = 2;</code>
   */
  com.google.protobuf.ByteString getData();
}
