// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package gRPC.com.protos;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Empty)
    com.google.protobuf.MessageOrBuilder {
}
