// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package gRPC.com.protos;

public interface IdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Id)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
