// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package gRPC.com.protos;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UsersList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UsersList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Id_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Id_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rexample.proto\"\007\n\005Empty\".\n\004User\022\n\n\002id\030\001" +
      " \001(\005\022\014\n\004name\030\002 \001(\t\022\014\n\004data\030\003 \001(\014\"\027\n\007User" +
      "DTO\022\014\n\004name\030\001 \001(\t\"!\n\tUsersList\022\024\n\005users\030" +
      "\001 \003(\0132\005.User\"\020\n\002Id\022\n\n\002id\030\001 \001(\005\"\'\n\013DataRe" +
      "quest\022\n\n\002id\030\001 \001(\005\022\014\n\004data\030\002 \001(\014\"\034\n\014DataR" +
      "esponse\022\014\n\004data\030\001 \001(\0142\350\001\n\013UserService\022#\n" +
      "\013GetAllUsers\022\006.Empty\032\n.UsersList\"\000\022\027\n\007Ge" +
      "tUser\022\003.Id\032\005.User\"\000\022 \n\nCreateUser\022\010.User" +
      "DTO\032\006.Empty\"\000\022#\n\007AddData\022\014.DataRequest\032\006" +
      ".Empty\"\000(\001\022!\n\007GetData\022\003.Id\032\r.DataRespons" +
      "e\"\0000\001\0221\n\014ExchangeData\022\014.DataRequest\032\r.Da" +
      "taResponse\"\000(\0010\001B\036\n\017gRPC.com.protosB\tUse" +
      "rProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "Id", "Name", "Data", });
    internal_static_UserDTO_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UserDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserDTO_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_UsersList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_UsersList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UsersList_descriptor,
        new java.lang.String[] { "Users", });
    internal_static_Id_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Id_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Id_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_DataRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_DataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataRequest_descriptor,
        new java.lang.String[] { "Id", "Data", });
    internal_static_DataResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_DataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataResponse_descriptor,
        new java.lang.String[] { "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
